// The child's actual English wordbooks, copied from the vocab app
// (C:\claude\english test\src\data — words.ts + wordsBridge.ts) so care-room
// quizzes practise the same words they study there. Read-only data.

export interface QuizWord {
  book: string;
  full: string;
  target: string;
  korean: string;
}

export const QUIZ_WORDS: QuizWord[] = [
  { book: "Tera A2", full: "jobless youth", target: "jobless", korean: "실업 청년" },
  { book: "Tera A2", full: "average student", target: "average", korean: "보통의 학생" },
  { book: "Tera A2", full: "wildlife habitat", target: "habitat", korean: "야생 동물 서식지" },
  { book: "Tera A2", full: "paranormal phenomena", target: "paranormal", korean: "초자연적 현상" },
  { book: "Tera A2", full: "artificial intelligence", target: "intelligence", korean: "인공 지능" },
  { book: "Tera A2", full: "formal dress", target: "formal", korean: "정장" },
  { book: "Tera A2", full: "inspire young artists", target: "inspire", korean: "젊은 예술가들에게 영감을 주다" },
  { book: "Tera A2", full: "purchase price", target: "purchase", korean: "구매 가격" },
  { book: "Tera A2", full: "deal with stress", target: "deal with", korean: "스트레스를 다루다" },
  { book: "Tera A2", full: "uncomfortable with criticism", target: "uncomfortable", korean: "비판을 불편해하다" },
  { book: "Tera A2", full: "hang out with friends", target: "hang out", korean: "친구들과 어울려 놀다" },
  { book: "Tera A2", full: "muscle pain", target: "muscle", korean: "근육통" },
  { book: "Tera A2", full: "detect a fire", target: "detect", korean: "화재를 감지하다" },
  { book: "Tera A2", full: "rely on parents", target: "rely on", korean: "부모에게 의존하다" },
  { book: "Tera A2", full: "extend the deadline", target: "extend", korean: "마감 기한을 연장하다" },
  { book: "Tera A2", full: "shell out a fortune", target: "shell out", korean: "거금을 들이다" },
  { book: "Tera A2", full: "rapid decrease in population", target: "rapid", korean: "급격한 인구 감소" },
  { book: "Tera A2", full: "rot teeth", target: "rot", korean: "치아를 썩게 하다" },
  { book: "Tera A2", full: "flight simulator", target: "simulator", korean: "비행 시뮬레이터" },
  { book: "Tera A2", full: "moderate exercise", target: "moderate", korean: "적당한 운동" },
  { book: "Tera A2", full: "temporary job", target: "temporary", korean: "임시직" },
  { book: "Tera A2", full: "urban planning", target: "urban", korean: "도시 계획" },
  { book: "Tera A2", full: "daily necessity", target: "necessity", korean: "생필품" },
  { book: "Tera A2", full: "well-known actor", target: "well-known", korean: "유명한 배우" },
  { book: "Tera A2", full: "take part in the exposition", target: "take part", korean: "박람회에 참여하다" },
  { book: "Tera A2", full: "college scholarship", target: "scholarship", korean: "대학 장학금" },
  { book: "Tera A2", full: "photo session", target: "session", korean: "사진 촬영(회), 포토 세션" },
  { book: "Tera A2", full: "Roman Empire", target: "Empire", korean: "로마 제국" },
  { book: "Tera A2", full: "prefer coffee to tea", target: "prefer", korean: "차보다 커피를 선호하다" },
  { book: "Tera A2", full: "French cuisine", target: "cuisine", korean: "프랑스 요리" },
  { book: "Tera A2", full: "indicate speed", target: "indicate", korean: "속도를 나타내다" },
  { book: "Tera A2", full: "public perception", target: "perception", korean: "대중의 인식" },
  { book: "Tera A2", full: "commitment to quality", target: "commitment", korean: "품질에 대한 전념" },
  { book: "Tera A2", full: "chirp back and forth", target: "chirp", korean: "(새 등이) 서로 지저귀다" },
  { book: "Tera A2", full: "take advantage of an opportunity", target: "take advantage of", korean: "기회를 활용하다" },
  { book: "Tera A2", full: "release heat", target: "release", korean: "열을 방출하다" },
  { book: "Tera A2", full: "original creator", target: "creator", korean: "최초의 창작자" },
  { book: "Tera A2", full: "alternative energy", target: "alternative", korean: "대체 에너지" },
  { book: "Tera A2", full: "generation gap", target: "generation", korean: "세대 차이" },
  { book: "Tera A2", full: "instead of milk", target: "instead", korean: "우유 대신에" },
  { book: "Tera A2", full: "sudden appearance", target: "appearance", korean: "갑작스러운 등장" },
  { book: "Tera A2", full: "transportation system", target: "system", korean: "교통 체계" },
  { book: "Tera A2", full: "deadly toxin", target: "toxin", korean: "치명적인 독소" },
  { book: "Tera A2", full: "travel destination", target: "destination", korean: "여행 목적지" },
  { book: "Tera A2", full: "close the window tightly", target: "tightly", korean: "창문을 꽉 닫다" },
  { book: "Tera A2", full: "road construction", target: "construction", korean: "도로 공사" },
  { book: "Tera A2", full: "cake decoration", target: "decoration", korean: "케이크 장식" },
  { book: "Tera A2", full: "regional differences", target: "regional", korean: "지역적 차이" },
  { book: "Tera A2", full: "efficient time management", target: "efficient", korean: "효율적인 시간 관리" },
  { book: "Tera A2", full: "technological innovation", target: "innovation", korean: "기술 혁신" },
  { book: "Tera A2", full: "metabolize food into energy", target: "metabolize", korean: "음식을 에너지로 대사하다" },
  { book: "Tera A2", full: "horrible nightmare", target: "nightmare", korean: "끔찍한 악몽" },
  { book: "Tera A2", full: "allow easy access", target: "allow", korean: "쉬운 접근을 허용하다" },
  { book: "Tera A2", full: "vivid description", target: "description", korean: "생생한 묘사" },
  { book: "Tera A2", full: "corporate headquarters", target: "headquarters", korean: "기업 본사" },
  { book: "Tera A2", full: "contest participant", target: "participant", korean: "대회 참가자" },
  { book: "Tera A2", full: "financial difficulties", target: "financial", korean: "재정적 어려움" },
  { book: "Tera A2", full: "take place by accident", target: "take place", korean: "우연히 발생하다" },
  { book: "Tera A2", full: "newborn infant", target: "infant", korean: "신생아" },
  { book: "Tera A2", full: "respectable politician", target: "respectable", korean: "존경할 만한 정치인" },
  { book: "Tera A2", full: "tourist attraction", target: "attraction", korean: "관광 명소" },
  { book: "Tera A2", full: "job applicant", target: "applicant", korean: "구직 지원자" },
  { book: "Tera A2", full: "attend a class", target: "attend", korean: "수업에 참석하다" },
  { book: "Tera A2", full: "pace nervously", target: "pace", korean: "초조하게 서성거리다" },
  { book: "Tera A2", full: "government policy", target: "policy", korean: "정부 정책" },
  { book: "Tera A2", full: "access the Internet", target: "access", korean: "인터넷에 접속하다" },
  { book: "Tera A2", full: "ancestor worship", target: "ancestor", korean: "조상 숭배" },
  { book: "Tera A2", full: "illegal immigrant", target: "immigrant", korean: "불법 이민자" },
  { book: "Tera A2", full: "fully-grown adult", target: "fully-grown", korean: "다 자란 성인" },
  { book: "Tera A2", full: "born skeptic", target: "skeptic", korean: "타고난 회의론자" },
  { book: "Tera A2", full: "originally developed in Korea", target: "originally", korean: "원래 한국에서 개발된" },
  { book: "Tera A2", full: "origin of life", target: "origin", korean: "생명의 기원" },
  { book: "Tera A2", full: "biologically rich island", target: "biologically", korean: "생물학적으로 풍부한 섬" },
  { book: "Tera A2", full: "elastic bracelet", target: "elastic", korean: "신축성 있는 팔찌" },
  { book: "Tera A2", full: "private life", target: "private", korean: "사생활" },
  { book: "Tera A2", full: "maintain balance", target: "maintain", korean: "균형을 유지하다" },
  { book: "Tera A2", full: "shrink in size", target: "shrink", korean: "크기가 줄어들다" },
  { book: "Tera A2", full: "competitive market", target: "competitive", korean: "경쟁적인 시장" },
  { book: "Tera A2", full: "invade other countries", target: "invade", korean: "다른 나라들을 침략하다" },
  { book: "Tera A2", full: "local lawmaker", target: "lawmaker", korean: "지역 의원" },
  { book: "Tera A2", full: "school counselor", target: "counselor", korean: "교내 상담가" },
  { book: "Tera A2", full: "threaten national security", target: "threaten", korean: "국가 안보를 위협하다" },
  { book: "Tera A2", full: "acoustic guitar", target: "acoustic", korean: "어쿠스틱 기타" },
  { book: "Tera A2", full: "hire an employee", target: "hire", korean: "직원을 고용하다" },
  { book: "Tera A2", full: "valuable jewelry", target: "valuable", korean: "귀중한 보석(류)" },
  { book: "Tera A2", full: "aged between 20 and 30", target: "aged", korean: "20세에서 30세 사이의" },
  { book: "Tera A2", full: "space tourism", target: "tourism", korean: "우주 관광" },
  { book: "Tera A2", full: "invest in stocks", target: "invest", korean: "주식에 투자하다" },
  { book: "Tera A2", full: "corporate headquarters", target: "corporate", korean: "기업 본사" },
  { book: "Tera A2", full: "enthusiastic crowd", target: "enthusiastic", korean: "열광적인 군중" },
  { book: "Tera A2", full: "starve to death", target: "starve", korean: "굶어 죽다" },
  { book: "Tera A2", full: "fairy tale book", target: "fairy tale", korean: "동화책" },
  { book: "Tera A2", full: "obviously correct answer", target: "obviously", korean: "명백히 정답인 답" },
  { book: "Tera A2", full: "function normally", target: "function", korean: "정상적으로 작동하다" },
  { book: "Tera A2", full: "limitless resources", target: "limitless", korean: "무한한 자원" },
  { book: "Tera A2", full: "intensive language course", target: "intensive", korean: "집중 어학 과정" },
  { book: "Tera A2", full: "determine the winner", target: "determine", korean: "승자를 결정하다" },
  { book: "Tera A2", full: "aggressive shark", target: "aggressive", korean: "공격적인 상어" },
  { book: "Tera A2", full: "gourmet food", target: "gourmet", korean: "고급 음식" },
  { book: "Tera A2", full: "defend human rights", target: "defend", korean: "인권을 옹호하다" },
  { book: "Bridge C1", full: "enchant the audience", target: "enchant", korean: "관중들을 매혹시키다" },
  { book: "Bridge C1", full: "portray a character", target: "portray", korean: "캐릭터를 묘사하다" },
  { book: "Bridge C1", full: "fossil fuel", target: "fossil", korean: "화석 연료" },
  { book: "Bridge C1", full: "present in nature", target: "present", korean: "자연 안에서 존재하는" },
  { book: "Bridge C1", full: "conquer the world", target: "conquer", korean: "세계를 정복하다" },
  { book: "Bridge C1", full: "remarkable achievement", target: "remarkable", korean: "주목할 만한 성과" },
  { book: "Bridge C1", full: "by luck or coincidence", target: "coincidence", korean: "운 혹은 우연의 일치" },
  { book: "Bridge C1", full: "theorize about the universe", target: "theorize", korean: "우주에 관하여 이론을 세우다" },
  { book: "Bridge C1", full: "genetic hair loss", target: "genetic", korean: "유전적 탈모" },
  { book: "Bridge C1", full: "historical perspective", target: "perspective", korean: "역사적 관점" },
  { book: "Bridge C1", full: "artificial limbs", target: "limbs", korean: "인공 팔다리" },
  { book: "Bridge C1", full: "mutant beast", target: "mutant", korean: "돌연변이의 짐승" },
  { book: "Bridge C1", full: "global phenomenon", target: "phenomenon", korean: "세계적인 현상" },
  { book: "Bridge C1", full: "realm of science", target: "realm", korean: "과학의 영역" },
  { book: "Bridge C1", full: "watch in fascination", target: "fascination", korean: "매료되어 관찰하다" },
  { book: "Bridge C1", full: "solid evidence", target: "solid", korean: "확실한 증거" },
  { book: "Bridge C1", full: "proof of identity", target: "proof", korean: "신원의 증거" },
  { book: "Bridge C1", full: "ancient civilization", target: "ancient", korean: "고대의 문명" },
  { book: "Bridge C1", full: "tiger claw", target: "claw", korean: "호랑이 발톱" },
  { book: "Bridge C1", full: "fish scales", target: "scales", korean: "물고기 비늘" },
  { book: "Bridge C1", full: "generous and kind", target: "generous", korean: "너그럽고 친절한" },
  { book: "Bridge C1", full: "greedy for money", target: "greedy", korean: "돈에 욕심 많은" },
  { book: "Bridge C1", full: "book hoarder", target: "hoarder", korean: "책 모아두는 사람" },
  { book: "Bridge C1", full: "mythical hero", target: "mythical", korean: "신화 속의 영웅" },
  { book: "Bridge C1", full: "socialization process", target: "socialization", korean: "사회화 과정" },
  { book: "Bridge C1", full: "affect health", target: "affect", korean: "건강에 영향을 미치다" },
  { book: "Bridge C1", full: "success factor", target: "factor", korean: "성공 요인" },
  { book: "Bridge C1", full: "responsible for the accident", target: "responsible for", korean: "그 사고에 책임이 있는" },
  { book: "Bridge C1", full: "adopt a positive attitude", target: "adopt", korean: "긍정적인 태도를 취하다" },
  { book: "Bridge C1", full: "Eastern values", target: "values", korean: "동양의 가치관" },
  { book: "Bridge C1", full: "uncommon opportunity", target: "uncommon", korean: "흔치 않은 기회" },
  { book: "Bridge C1", full: "influence the outcome", target: "influence", korean: "결과에 영향을 미치다" },
  { book: "Bridge C1", full: "words and behavior", target: "behavior", korean: "말과 행동" },
  { book: "Bridge C1", full: "father-son relationship", target: "relationship", korean: "아버지-아들의 관계 = 부자관계" },
  { book: "Bridge C1", full: "expand business", target: "expand", korean: "사업을 확장하다" },
  { book: "Bridge C1", full: "gender equality", target: "gender", korean: "성 평등" },
  { book: "Bridge C1", full: "character flaw", target: "character", korean: "성격 결함" },
  { book: "Bridge C1", full: "expose the skin to sunlight", target: "expose", korean: "햇빛에 피부를 노출시키다" },
  { book: "Bridge C1", full: "overall impression", target: "overall", korean: "전반적인 인상" },
  { book: "Bridge C1", full: "cannibal tribe", target: "tribe", korean: "식인 부족" },
  { book: "Bridge C1", full: "village elders", target: "elders", korean: "마을 원로들" },
  { book: "Bridge C1", full: "represent peace", target: "represent", korean: "평화를 상징하다" },
  { book: "Bridge C1", full: "military discipline", target: "discipline", korean: "군대 규율" },
  { book: "Bridge C1", full: "spiritual leader", target: "spiritual", korean: "정신적인 지도자" },
  { book: "Bridge C1", full: "miniature Christmas tree", target: "miniature", korean: "소형의 크리스마스 트리" },
  { book: "Bridge C1", full: "bow and arrow", target: "bow", korean: "활과 화살" },
  { book: "Bridge C1", full: "religious ritual", target: "ritual", korean: "종교적인 의식" },
  { book: "Bridge C1", full: "handy tool", target: "handy", korean: "유용한 도구" },
  { book: "Bridge C1", full: "survival of the fittest", target: "survival", korean: "적자 생존(환경에 적응하는 종만 살아남는다)" },
  { book: "Bridge C1", full: "garbage disposal", target: "garbage", korean: "쓰레기 처리" },
  { book: "Bridge C1", full: "devastate a village", target: "devastate", korean: "마을을 폐허로 만들어버리다" },
  { book: "Bridge C1", full: "swallow a pill", target: "swallow", korean: "알약을 삼키다." },
  { book: "Bridge C1", full: "significant discovery", target: "significant", korean: "중요한 발견" },
  { book: "Bridge C1", full: "as hard as brick", target: "brick", korean: "벽돌처럼 단단한" },
  { book: "Bridge C1", full: "sturdy legs", target: "sturdy", korean: "튼튼한 다리" },
  { book: "Bridge C1", full: "fireproof clothes", target: "fireproof", korean: "방화복" },
  { book: "Bridge C1", full: "deadly virus", target: "deadly", korean: "치명적인 바이러스" },
  { book: "Bridge C1", full: "cholera plague", target: "plague", korean: "콜레라 전염병" },
  { book: "Bridge C1", full: "unsanitary food", target: "unsanitary", korean: "비위생적인 음식" },
  { book: "Bridge C1", full: "spread of a rumor", target: "spread", korean: "루머의 확산" },
  { book: "Bridge C1", full: "school dress code", target: "code", korean: "학교 복장 규정" },
  { book: "Bridge C1", full: "restrict access", target: "restrict", korean: "접근을 제한하다" },
  { book: "Bridge C1", full: "construct a bridge", target: "construct", korean: "다리를 건설하다" },
  { book: "Bridge C1", full: "organize the desk", target: "organize", korean: "책상을 정리하다" },
  { book: "Bridge C1", full: "schedule management", target: "management", korean: "일정 관리" },
  { book: "Bridge C1", full: "military capability", target: "capability", korean: "군사력" },
  { book: "Bridge C1", full: "take the failure as a blessing in disguise", target: "blessing in disguise", korean: "실패를 전화위복으로 여기다" },
  { book: "Bridge C1", full: "wipe out malaria", target: "wipe out", korean: "말라리아를 완전히 없애버리다" },
  { book: "Bridge C1", full: "entire country", target: "entire", korean: "전체 국가" },
  { book: "Bridge C1", full: "note the difference", target: "note", korean: "차이점에 주목하다" },
  { book: "Bridge C1", full: "flea bite", target: "flea", korean: "벼룩 물림" },
  { book: "Bridge C1", full: "21st century", target: "century", korean: "21 세기" },
  { book: "Bridge C1", full: "silly mistake", target: "silly", korean: "바보 같은 실수" },
  { book: "Bridge C1", full: "death toll", target: "death", korean: "사망자 수" },
  { book: "Bridge C1", full: "triumph over evil", target: "triumph", korean: "악에서 승리하다" },
  { book: "Bridge C1", full: "imaginary animal", target: "imaginary", korean: "상상의 동물" },
  { book: "Bridge C1", full: "thrive during a crisis", target: "thrive", korean: "위기 동안에 잘 자라다" },
  { book: "Bridge C1", full: "escape from the prison", target: "escape", korean: "감옥으로부터 탈출하다" },
  { book: "Bridge C1", full: "go beyond reality", target: "go beyond", korean: "현실을 초월하다" },
  { book: "Bridge C1", full: "seek a breakthrough", target: "seek", korean: "돌파구를 모색하다" },
  { book: "Bridge C1", full: "geographical location", target: "geographical", korean: "지리적인 위치" },
  { book: "Bridge C1", full: "vivid description", target: "vivid", korean: "생생한 묘사" },
  { book: "Bridge C1", full: "fictional character", target: "fictional", korean: "허구적인 캐릭터" },
  { book: "Bridge C1", full: "theme song", target: "theme", korean: "주제가" },
  { book: "Bridge C1", full: "struggle to survive", target: "struggle", korean: "생존을 위해 안간힘을 쓰다" },
  { book: "Bridge C1", full: "root for the home team", target: "root for", korean: "홈 팀을 응원하다" },
  { book: "Bridge C1", full: "victorious army", target: "victorious", korean: "승리한 군대" },
  { book: "Bridge C1", full: "dreary gray sky", target: "dreary", korean: "우중충한 회색 하늘" },
  { book: "Bridge C1", full: "believable excuse", target: "believable", korean: "그럴듯한 변명" },
  { book: "Bridge C1", full: "typical Hollywood movie", target: "typical", korean: "전형적인 할리우드 영화" },
  { book: "Bridge C1", full: "set out on a journey", target: "set out", korean: "여행을 떠나다" },
  { book: "Bridge C1", full: "movie trilogy", target: "trilogy", korean: "영화 3부작" },
  { book: "Bridge C1", full: "evil spirit", target: "evil", korean: "악한 정신" },
  { book: "Bridge C1", full: "evil force", target: "force", korean: "악의 세력" },
  { book: "Bridge C1", full: "rain constantly", target: "constantly", korean: "끊임없이 비가 오다" },
  { book: "Bridge C1", full: "defeat the enemy", target: "defeat", korean: "적을 물리치다" },
  { book: "Bridge C1", full: "youth fellowship", target: "fellowship", korean: "청년 단체" },
  { book: "Bridge C1", full: "swear to tell the truth", target: "swear", korean: "진실을 말하겠다고 맹세하다" },
  { book: "Bridge C1", full: "appealing proposal", target: "appealing", korean: "매력적인 제안" },
];
